# Generated by Django 4.2.7 on 2024-01-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0002_alter_about_career_alter_about_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pdf', models.FileField(max_length=200, upload_to='certifications_pdfs/')),
            ],
        ),
    ]
