# Generated by Django 4.2.7 on 2024-01-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0003_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(default=1, upload_to='certifications_images/'),
            preserve_default=False,
        ),
    ]
